/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author haffi
 */
public class FrmPrincipiante extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipiante
     */
    public FrmPrincipiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnActivar = new javax.swing.JButton();
        btnResultadosP = new javax.swing.JButton();
        btnNivelP = new javax.swing.JButton();
        jlbSuma1 = new javax.swing.JLabel();
        jlbSuma2 = new javax.swing.JLabel();
        txtSuma2 = new javax.swing.JTextField();
        jlbNo7 = new javax.swing.JLabel();
        jlbAciertos4 = new javax.swing.JLabel();
        jlbNo8 = new javax.swing.JLabel();
        jlbfallas4 = new javax.swing.JLabel();
        jlbintentos4 = new javax.swing.JLabel();
        txtResta1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jlbintentos5 = new javax.swing.JLabel();
        txtResta2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jlbNo9 = new javax.swing.JLabel();
        jlbAciertos5 = new javax.swing.JLabel();
        jlbNo10 = new javax.swing.JLabel();
        jlbfallas5 = new javax.swing.JLabel();
        jlbAciertos = new javax.swing.JLabel();
        jlbfallas = new javax.swing.JLabel();
        jlbintentos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbNo1 = new javax.swing.JLabel();
        jlbAciertos1 = new javax.swing.JLabel();
        jlbNo2 = new javax.swing.JLabel();
        jlbfallas1 = new javax.swing.JLabel();
        jlbintentos1 = new javax.swing.JLabel();
        txtResultado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbNo3 = new javax.swing.JLabel();
        jlbAciertos2 = new javax.swing.JLabel();
        jlbNo4 = new javax.swing.JLabel();
        jlbfallas2 = new javax.swing.JLabel();
        jlbintentos2 = new javax.swing.JLabel();
        txtResultado3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlbintentos3 = new javax.swing.JLabel();
        txtResultado4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jlbNo5 = new javax.swing.JLabel();
        jlbAciertos3 = new javax.swing.JLabel();
        jlbNo6 = new javax.swing.JLabel();
        jlbfallas3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nivel Principiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/start.png"))); // NOI18N
        btnActivar.setText("Iniciar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnResultadosP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btnResultadosP.setText("Calificar");
        btnResultadosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosPActionPerformed(evt);
            }
        });

        btnNivelP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/up.png"))); // NOI18N
        btnNivelP.setText("Siguiente Nivel");

        jlbSuma1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbSuma1.setText("#1");

        jlbSuma2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbSuma2.setText("#2");

        txtSuma2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSuma2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuma2KeyTyped(evt);
            }
        });

        jlbNo7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo7.setText("#1");

        jlbAciertos4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAciertos4.setText("0");

        jlbNo8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo8.setText("#2");

        jlbfallas4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbfallas4.setText("0");

        jlbintentos4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbintentos4.setText("0");

        txtResta1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResta1KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("-");

        jlbintentos5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbintentos5.setText("0");

        txtResta2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResta2KeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("-");

        jlbNo9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo9.setText("#1");

        jlbAciertos5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAciertos5.setText("0");

        jlbNo10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo10.setText("#2");

        jlbfallas5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbfallas5.setText("0");

        jlbAciertos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAciertos.setText("0");

        jlbfallas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbfallas.setText("0");

        jlbintentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbintentos.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Aciertos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Fallos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Intentos");

        jlbNo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo1.setText("#1");

        jlbAciertos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAciertos1.setText("0");

        jlbNo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo2.setText("#2");

        jlbfallas1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbfallas1.setText("0");

        jlbintentos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbintentos1.setText("0");

        txtResultado2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResultado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado2KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("+");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("+");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ingrese sus respuestas");

        jlbNo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo3.setText("#1");

        jlbAciertos2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAciertos2.setText("0");

        jlbNo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo4.setText("#2");

        jlbfallas2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbfallas2.setText("0");

        jlbintentos2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbintentos2.setText("0");

        txtResultado3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResultado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado3KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("*");

        jlbintentos3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbintentos3.setText("0");

        txtResultado4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResultado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado4KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("/");

        jlbNo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo5.setText("#1");

        jlbAciertos3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAciertos3.setText("0");

        jlbNo6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNo6.setText("#2");

        jlbfallas3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbfallas3.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActivar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResultadosP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNivelP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbNo9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbNo10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbNo7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbNo8)))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlbSuma1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbSuma2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlbNo3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbNo4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlbNo5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbNo6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlbNo1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlbNo2)))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtResultado3)
                                                .addComponent(txtResultado4)
                                                .addComponent(txtResta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSuma2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtResta2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(57, 57, 57)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbAciertos3)
                                            .addComponent(jlbAciertos1)
                                            .addComponent(jlbAciertos2)
                                            .addComponent(jlbAciertos5)
                                            .addComponent(jlbAciertos4)
                                            .addComponent(jlbAciertos))
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlbfallas5)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlbfallas4)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jlbfallas1)
                                                    .addComponent(jlbfallas)
                                                    .addComponent(jlbfallas2)
                                                    .addComponent(jlbfallas3))))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbintentos)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlbintentos1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jlbintentos2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jlbintentos3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jlbintentos4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jlbintentos5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))))
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jlbintentos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSuma1)
                            .addComponent(jlbSuma2)
                            .addComponent(jLabel4)
                            .addComponent(txtSuma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNo1)
                            .addComponent(jlbNo2)
                            .addComponent(jLabel5)
                            .addComponent(txtResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbAciertos1)
                            .addComponent(jlbfallas1)
                            .addComponent(jlbintentos1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNo3)
                                    .addComponent(jlbNo4)
                                    .addComponent(jLabel7))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNo5)
                                    .addComponent(jlbNo6)
                                    .addComponent(jLabel8)))
                            .addComponent(txtResultado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbNo7)
                                .addComponent(jlbNo8)
                                .addComponent(jLabel9))
                            .addComponent(txtResta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNo9)
                                    .addComponent(jlbNo10)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtResta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbfallas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbAciertos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbintentos2)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jlbAciertos2)
                                                .addComponent(jlbfallas2)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbintentos3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbAciertos3)
                                        .addComponent(jlbfallas3)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlbAciertos5)
                                            .addComponent(jlbfallas5)
                                            .addComponent(jlbintentos5)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlbAciertos4)
                                            .addComponent(jlbfallas4)
                                            .addComponent(jlbintentos4))))))))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNivelP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnResultadosP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultadosPActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarActionPerformed

    private void txtSuma2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuma2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtSuma2KeyTyped

    private void txtResultado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResultado2KeyTyped

    private void txtResultado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado3KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResultado3KeyTyped

    private void txtResultado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado4KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResultado4KeyTyped

    private void txtResta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResta1KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResta1KeyTyped

    private void txtResta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResta2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResta2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivar;
    public javax.swing.JButton btnNivelP;
    public javax.swing.JButton btnResultadosP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlbAciertos;
    public javax.swing.JLabel jlbAciertos1;
    public javax.swing.JLabel jlbAciertos2;
    public javax.swing.JLabel jlbAciertos3;
    public javax.swing.JLabel jlbAciertos4;
    public javax.swing.JLabel jlbAciertos5;
    public javax.swing.JLabel jlbNo1;
    public javax.swing.JLabel jlbNo10;
    public javax.swing.JLabel jlbNo2;
    public javax.swing.JLabel jlbNo3;
    public javax.swing.JLabel jlbNo4;
    public javax.swing.JLabel jlbNo5;
    public javax.swing.JLabel jlbNo6;
    public javax.swing.JLabel jlbNo7;
    public javax.swing.JLabel jlbNo8;
    public javax.swing.JLabel jlbNo9;
    public javax.swing.JLabel jlbSuma1;
    public javax.swing.JLabel jlbSuma2;
    public javax.swing.JLabel jlbfallas;
    public javax.swing.JLabel jlbfallas1;
    public javax.swing.JLabel jlbfallas2;
    public javax.swing.JLabel jlbfallas3;
    public javax.swing.JLabel jlbfallas4;
    public javax.swing.JLabel jlbfallas5;
    public javax.swing.JLabel jlbintentos;
    public javax.swing.JLabel jlbintentos1;
    public javax.swing.JLabel jlbintentos2;
    public javax.swing.JLabel jlbintentos3;
    public javax.swing.JLabel jlbintentos4;
    public javax.swing.JLabel jlbintentos5;
    public javax.swing.JTextField txtResta1;
    public javax.swing.JTextField txtResta2;
    public javax.swing.JTextField txtResultado2;
    public javax.swing.JTextField txtResultado3;
    public javax.swing.JTextField txtResultado4;
    public javax.swing.JTextField txtSuma2;
    // End of variables declaration//GEN-END:variables
}
